name: 'ClickHouse DB'
description: 'ClickHouse DB as an action to automate some tests'
author: 'praneeth527ct'
branding:
  icon: 'database'
  color: 'yellow'
inputs:
  # See https://hub.docker.com/r/clickhouse/clickhouse-server/ for supported versions
  version:
    description: 'ClickHouse version to use'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}