name: "dbt-docs-publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    env:
      DBT_TARGET: ${{vars.DBT_TARGET}}
      DBT_PROFILES_DIR: ${{ github.workspace }}/projects
      CLICKHOUSE_USER: ${{vars.CLICKHOUSE_USER}}
      CLICKHOUSE_PASSWORD: ${{vars.CLICKHOUSE_PASSWORD}}
      CLICKHOUSE_DATABASE: ${{vars.CLICKHOUSE_DATABASE}}
      CLICKHOUSE_HOST: localhost
      CLICKHOUSE_PORT: 8123

    steps:
      - name: "Step 01 - Checkout current branch"
        id: step01
        uses: actions/checkout@v3

      - name: "Step 02 - Install dbt"
        id: step02
        run: |
          pip3 install dbt-core dbt-clickhouse
          dbt --version

      - name: "Step 03 - Setup ClickHouse"
        id: step03
        uses: praneeth527/clickhouse-server-action@v1.0.1
        with:
          tag: '23.3.18.15-alpine'

      - name: "Step 04 - Generate dbt docs"
        id: step04
        uses: praneeth527/generate-dbt-docs@v1
        with:
          projects_dir: projects
          docs_dir: ${{ github.workspace }}/docs


      - name: "Step 05 - Upload pages to artifact"
        id: step05
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs


  deploy-to-github-pages:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4