jaffle_shop:
  target: dev  # Default target, you can change this to switch environments
  outputs:
    dev:
      type: clickhouse
      schema: dbt_test
      host: localhost
      port: 8123
      user: {{ env_var('USERNAME') }}
      password: {{ env_var('PASSWORD') }}